"""Initialize db

Revision ID: 04e6eafaf8ee
Revises: 57881204f4e6
Create Date: 2024-02-03 18:46:18.538317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e6eafaf8ee'
down_revision = '57881204f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
